
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

#if defined(__FreeBSD__)
#ifndef __STDC_LIMIT_MACROS
#define	__STDC_LIMIT_MACROS
#endif
#include <sys/cdefs.h>
#include <stdint.h>
#else
#define	__dead2
#endif

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined(__FreeBSD__) || \
    (defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L)

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
#define yy_current_buffer YY_CURRENT_BUFFER

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  ) __dead2;

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[535] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   85,   84,   74,   75,
       84,   76,   79,   83,   83,   78,   77,   80,   81,   82,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,    2,    2,    2,    4,    4,
        4,   77,   83,   83,   45,   83,   83,   46,   52,   52,
       52,   65,   65,   65,   84,    6,    6,    6,   84,   36,
       83,   74,    0,   73,   76,   83,   77,   83,   77,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,

       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   17,    2,    2,
        2,    2,    4,    4,    4,    4,    8,    8,   45,   83,
       45,   44,   43,   52,   52,   52,   52,   65,   65,   65,
       65,    0,   69,    6,    6,    6,    6,    0,   72,   36,
       37,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   56,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   55,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       36,   83,   83,   83,   83,   83,   83,   83,   83,   83,

        7,   83,   83,    3,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,    5,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   15,
       83,   83,   83,   83,   83,   83,   83,   83,   41,   83,
       83,   83,   83,   83,   83,   83,   22,   21,   83,   83,
       83,   83,   83,   67,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   16,   83,   83,   66,   83,   83,
       83,   83,   83,   83,   83,   83,    8,   37,   83,   83,
       83,   83,   83,   83,   83,   83,   70,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,

       83,   19,   83,   10,   83,   83,   83,   83,   83,   83,
       12,   68,   83,   48,   83,   83,   62,    9,   83,   83,
       83,   57,   83,   83,   61,   83,   71,   83,   83,   83,
       64,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   14,   83,   49,   60,   83,   83,
       83,   83,   83,   83,   59,   42,   50,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   53,   83,   83,
       58,   83,   83,   83,   54,   83,   83,   83,   83,   83,
        1,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   13,   83,   83,   83,

       83,   83,   83,   83,   83,   11,   83,   83,   35,   83,
       83,   83,   83,   83,   24,   83,   63,   83,   83,   83,
       83,   27,   83,   83,   34,   83,   18,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   20,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   51,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   29,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   40,   83,   83,   31,   83,   83,   47,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,

       83,   83,   83,   83,   28,   83,   83,   83,   25,   83,
       83,   83,   23,   83,   30,   83,   83,   32,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   38,   83,   26,
       83,   39,   33,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    6,    7,    8,    9,   10,   10,   10,
       10,   10,   11,   10,   10,   10,   10,   12,   13,    1,
        1,    1,    1,    1,   14,   15,   16,   17,   15,   15,
       18,   19,   18,   18,   18,   18,   20,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        1,    1,    1,    1,   18,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   18,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   18,   45,    1,   46,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    1,    3,
        3,    3,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1
    } ;

static yyconst flex_int16_t yy_base[551] =
    {   0,
        0,   46,   74,    0,  113,  159,    0,    0,  205,  251,
      288,    0,    8,   25,  314,  360,  406,  452,  835,  834,
      498,  544,  833,  832,  581,    0,  835,  840,  832,  840,
      829,    0,  840,    0,    4,  840,   12,  840,  840,  840,
      812,    0,  808,    4,  787,    0,    4,  804,  794,   32,
      792,    5,   41,   44,  792,    0,   16,   66,    0,   53,
       70,  600,   74,   76,  117,  804,  800,  840,    0,   78,
      121,    0,   90,  125,  819,    0,  127,  131,  818,  617,
      135,  819,  816,  840,    0,    0,  137,  139,  143,  805,
      794,   41,  778,  784,  784,  782,  784,  777,  790,  772,

      802,  801,   71,  763,  773,  767,  769,  764,  768,  132,
      138,  769,  153,  763,   97,  764,  777,    0,    0,  145,
      167,  173,    0,  175,  177,  182,  186,  785,  189,  191,
      209,    0,    0,    0,  211,  213,  217,    0,  219,  221,
      225,  792,  840,    0,  227,  229,  233,  791,  840,  237,
      782,  777,  755,  757,  756,  761,  765,  766,  765,  761,
      755,  760,  743,  230,  760,  749,  237,  754,  749,  743,
      168,  769,  746,  743,  747,  733,  744,  741,  762,    0,
      737,  733,  729,  725,  735,  726,  738,  754,  753,  634,
      259,  651,   10,  734,  721,  715,  731,  717,  710,  724,

        0,  715,  251,    0,  730,  726,  711,  708,  714,  709,
      708,  158,  721,  188,  736,  704,  700,    0,   54,  671,
      679,  679,  664,  665,  655,  662,  661,  646,  655,    0,
      633,  243,  668,  685,  650,  652,  626,  634,    0,  621,
      646,  627,  614,  621,  605,  612,    0,    0,  597,  606,
      600,  588,  593,    0,  592,  579,  578,  584,  244,  576,
      567,  562,  551,  570,    0,  581,  552,    0,  560,  547,
      546,  544,  543,  556,  556,  554,  566,  565,  559,  564,
      536,  534,  533,  533,  546,  562,    0,  544,  556,  532,
      540,  525,  542,  541,  527,  520,  527,  521,  522,  526,

      505,    0,  516,  533,  505,  515,  498,  507,  507,  495,
        0,    0,  496,    0,  499,  520,    0,  523,  501,  499,
      502,  496,  492,  513,    0,  500,    0,  478,  482,  497,
        0,  486,  497,  476,  484,  478,  473,  480,  483,  479,
      471,  467,  468,  455,    0,  452,    0,    0,  457,  459,
      467,  452,  463,  466,    0,    0,    0,  457,  460,  445,
      454,  457,  460,  439,  454,  455,  444,    0,  444,  441,
        0,  445,  448,  438,    0,  450,  429,  425,  436,  433,
        0,  441,  431,  422,  421,  424,  411,  422,  407,  413,
      411,  411,  405,  407,  401,  414,    0,  413,  404,  399,

      428,  427,  400,  395,  393,    0,  405,  400,    0,  403,
      420,  395,  396,  387,  416,  415,    0,  388,  252,  413,
      411,    0,  376,  365,    0,  254,    0,  369,  395,  363,
      366,  378,  374,  363,  363,  256,  369,    0,  370,  359,
      359,  260,  366,  357,  357,  364,  355,  365,  361,  350,
      362,  358,  349,    0,  356,  345,  341,  346,  351,  338,
      353,  340,  343,  326,  334,  319,  334,  330,  321,  311,
      307,    0,  325,  320,  323,  310,  325,  320,  319,  314,
      305,  320,  315,    0,  301,  305,    0,  312,  307,    0,
      297,  301,  308,  303,  294,  292,  322,  290,  293,  283,

      301,  269,  273,  263,    0,  267,  257,  287,    0,  260,
      254,  284,    0,  269,    0,  256,  267,    0,  254,  254,
      264,  247,  225,  217,  202,  170,  120,    0,  119,    0,
      115,    0,    0,  840,  711,  714,  717,  720,  723,  726,
      729,  732,  131,  102,   87,   18,    9,  735,    4,  738
    } ;

static yyconst flex_int16_t yy_def[551] =
    {   0,
      535,  535,    2,    3,  536,  536,    2,    2,  537,  537,
        2,   11,    2,    2,  538,  538,  539,  539,    2,    2,
      540,  540,    2,    2,    2,   25,  534,  534,  534,  534,
      541,  542,  534,  543,  543,  534,  543,  534,  534,  534,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  544,  544,  544,  545,  545,
      545,  543,   62,  543,  543,  543,  543,  534,  546,  546,
      546,  547,  547,  547,  548,  549,  549,  549,  550,   62,
       80,  534,  541,  534,  542,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,

      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  544,  544,
      544,  544,  545,  545,  545,  545,  543,  543,  543,  543,
      543,  543,  543,  546,  546,  546,  546,  547,  547,  547,
      547,  548,  534,  549,  549,  549,  549,  550,  534,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,

      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,

      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,

      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,

      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,  543,  543,  543,  543,  543,  543,  543,
      543,  543,  543,    0,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534
    } ;

static yyconst flex_int16_t yy_nxt[887] =
    {   0,
       28,   29,   30,   31,   32,   33,  144,   35,   36,   37,
       37,  138,   38,   87,   87,   64,  235,   65,   65,   88,
      134,   89,   89,   91,  101,  120,  120,  102,   95,  236,
       92,   99,   64,  100,   65,   65,  103,   96,  109,   93,
       66,  110,   67,   97,   39,   40,   28,   29,   30,   31,
       32,   33,   68,   35,   36,   37,   37,   66,   38,   67,
      106,  111,  124,  124,  112,  113,  114,  154,  115,   68,
      107,  155,  116,  121,  117,  122,  122,  125,  262,  126,
      126,   86,  263,  128,  128,  129,  129,  135,  135,  123,
       39,   40,   41,  166,   42,   43,  167,   44,   45,  139,

      139,   46,   47,   48,  119,   49,   50,   51,   52,  168,
       53,   54,   55,   28,   29,   30,   31,   32,   33,  186,
       57,   36,   58,   58,  130,   38,  131,  131,  136,  187,
      137,  137,  140,   86,  141,  141,  145,  145,  146,  533,
      147,  147,   86,  532,  151,  151,   87,   87,   87,   87,
       88,  531,   89,   89,  120,  120,  175,   39,   40,   28,
       29,   30,   31,   32,   33,  176,   57,   36,   58,   58,
      177,   38,  178,  181,  214,  182,  120,  120,  183,  179,
      121,  254,  122,  122,  124,  124,  124,  124,  184,  125,
      255,  126,  126,   88,  530,   89,   89,  190,  129,  129,

      129,  129,  215,   39,   40,   28,   29,   30,   31,   32,
       33,  257,   60,   36,   61,   61,  130,   38,  131,  131,
      135,  135,  135,  135,  136,  258,  137,  137,  139,  139,
      139,  139,  140,  529,  141,  141,  145,  145,  145,  145,
      146,  528,  147,  147,   88,  527,  191,  191,  192,   39,
       40,   28,   29,   30,   31,   32,   33,  245,   60,   36,
       61,   61,  205,   38,  206,  209,   88,  299,  191,  191,
      210,  275,  433,  276,  439,  434,  449,  440,  526,  450,
      455,  300,  246,  456,  525,  524,  523,  522,  521,  520,
      519,  518,  517,  516,  515,   39,   40,   62,   62,  514,

      513,   63,   63,   63,   63,  512,  511,  510,   63,   63,
       63,   63,   63,   63,   28,   29,   30,   31,   32,   33,
      509,   70,   36,   71,   71,  508,   38,  507,  506,  505,
      504,  503,  502,  501,  500,  499,  498,  497,  496,  495,
      494,  493,  492,  491,  490,  489,  488,  487,  486,  485,
      484,  483,  482,  481,  480,  479,  478,  477,   39,   40,
       28,   29,   30,   31,   32,   33,  476,   70,   36,   71,
       71,  475,   38,  474,  473,  472,  471,  470,  469,  468,
      467,  466,  465,  464,  463,  462,  461,  460,  459,  458,
      457,  454,  453,  452,  451,  448,  447,  446,  445,  444,

      443,  442,  441,  438,   39,   40,   28,   29,   30,   31,
       32,   33,  437,   73,   36,   74,   74,  436,   38,  435,
      432,  431,  430,  429,  428,  427,  426,  425,  424,  423,
      422,  421,  420,  419,  418,  417,  416,  415,  414,  413,
      412,  411,  410,  409,  408,  407,  406,  405,  404,  403,
       39,   40,   28,   29,   30,   31,   32,   33,  402,   73,
       36,   74,   74,  401,   38,  400,  399,  398,  397,  396,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  381,  380,  379,  378,  377,  376,
      375,  374,  373,  372,  371,  370,   39,   40,   28,   29,

       30,   31,   32,   33,  369,   77,   36,   78,   78,  368,
       38,  367,  366,  365,  364,  363,  362,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,   39,   40,   28,   29,   30,   31,   32,   33,
      336,   77,   36,   78,   78,  335,   38,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  192,  190,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,   39,   40,
       80,   80,  305,  304,   81,   81,   81,   81,  303,  302,

      301,   81,   81,   81,   81,   81,   81,   88,  298,  127,
      127,  297,  296,  128,  128,  128,  128,  295,  294,  293,
      128,  128,  128,  128,  128,  128,  150,  150,  292,  291,
      151,  151,  151,  151,  290,  289,  288,  151,  151,  151,
      151,  151,  151,  233,  233,  287,  286,  233,  233,  233,
      233,  285,  284,  283,  233,  233,  233,  233,  233,  233,
      234,  234,  282,  281,  234,  234,  234,  234,  280,  279,
      274,  234,  234,  234,  234,  234,  234,  277,  277,  273,
      272,  277,  277,  277,  277,  271,  270,  269,  277,  277,
      277,  277,  277,  277,  278,  278,  268,  267,  278,  278,

      278,  278,  266,  265,  264,  278,  278,  278,  278,  278,
      278,   34,   34,   34,   56,   56,   56,   59,   59,   59,
       69,   69,   69,   72,   72,   72,   76,   76,   76,   83,
       83,   83,   85,  261,   85,  142,  142,  142,  148,  148,
      148,  260,  259,  256,  253,  252,  251,  250,  249,  248,
      247,  244,  243,  242,  241,  240,  239,  238,  237,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  213,  212,  211,  208,
      207,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  149,  143,  190,  189,  188,  185,

      180,  174,  173,  172,  171,  170,  169,  165,  164,  163,
      162,  161,  160,  159,  158,  157,  156,  153,  152,   84,
       82,  149,  143,  133,  132,  118,  108,  105,  104,   98,
       94,   90,   84,   82,  534,   79,   79,   75,   75,   27,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534
    } ;

static yyconst flex_int16_t yy_chk[887] =
    {   0,
        1,    1,    1,    1,    1,    1,  549,    1,    1,    1,
        1,  547,    1,   35,   35,   13,  193,   13,   13,   37,
      546,   37,   37,   42,   47,   57,   57,   47,   44,  193,
       42,   46,   14,   46,   14,   14,   47,   44,   52,   42,
       13,   52,   13,   44,    1,    1,    2,    2,    2,    2,
        2,    2,   13,    2,    2,    2,    2,   14,    2,   14,
       50,   53,   60,   60,   53,   53,   54,   92,   54,   14,
       50,   92,   54,   58,   54,   58,   58,   61,  219,   61,
       61,   63,  219,   63,   63,   64,   64,   70,   70,  545,
        2,    2,    3,  103,    3,    3,  103,    3,    3,   73,

       73,    3,    3,    3,  544,    3,    3,    3,    3,  103,
        3,    3,    3,    5,    5,    5,    5,    5,    5,  115,
        5,    5,    5,    5,   65,    5,   65,   65,   71,  115,
       71,   71,   74,  543,   74,   74,   77,   77,   78,  531,
       78,   78,   81,  529,   81,   81,   87,   87,   88,   88,
       89,  527,   89,   89,  120,  120,  110,    5,    5,    6,
        6,    6,    6,    6,    6,  110,    6,    6,    6,    6,
      111,    6,  111,  113,  171,  113,  121,  121,  113,  111,
      122,  212,  122,  122,  124,  124,  125,  125,  113,  126,
      212,  126,  126,  127,  526,  127,  127,  127,  129,  129,

      130,  130,  171,    6,    6,    9,    9,    9,    9,    9,
        9,  214,    9,    9,    9,    9,  131,    9,  131,  131,
      135,  135,  136,  136,  137,  214,  137,  137,  139,  139,
      140,  140,  141,  525,  141,  141,  145,  145,  146,  146,
      147,  524,  147,  147,  150,  523,  150,  150,  150,    9,
        9,   10,   10,   10,   10,   10,   10,  203,   10,   10,
       10,   10,  164,   10,  164,  167,  191,  259,  191,  191,
      167,  232,  419,  232,  426,  419,  436,  426,  522,  436,
      442,  259,  203,  442,  521,  520,  519,  517,  516,  514,
      512,  511,  510,  508,  507,   10,   10,   11,   11,  506,

      504,   11,   11,   11,   11,  503,  502,  501,   11,   11,
       11,   11,   11,   11,   15,   15,   15,   15,   15,   15,
      500,   15,   15,   15,   15,  499,   15,  498,  497,  496,
      495,  494,  493,  492,  491,  489,  488,  486,  485,  483,
      482,  481,  480,  479,  478,  477,  476,  475,  474,  473,
      471,  470,  469,  468,  467,  466,  465,  464,   15,   15,
       16,   16,   16,   16,   16,   16,  463,   16,   16,   16,
       16,  462,   16,  461,  460,  459,  458,  457,  456,  455,
      453,  452,  451,  450,  449,  448,  447,  446,  445,  444,
      443,  441,  440,  439,  437,  435,  434,  433,  432,  431,

      430,  429,  428,  424,   16,   16,   17,   17,   17,   17,
       17,   17,  423,   17,   17,   17,   17,  421,   17,  420,
      418,  416,  415,  414,  413,  412,  411,  410,  408,  407,
      405,  404,  403,  402,  401,  400,  399,  398,  396,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  385,
       17,   17,   18,   18,   18,   18,   18,   18,  384,   18,
       18,   18,   18,  383,   18,  382,  380,  379,  378,  377,
      376,  374,  373,  372,  370,  369,  367,  366,  365,  364,
      363,  362,  361,  360,  359,  358,  354,  353,  352,  351,
      350,  349,  346,  344,  343,  342,   18,   18,   21,   21,

       21,   21,   21,   21,  341,   21,   21,   21,   21,  340,
       21,  339,  338,  337,  336,  335,  334,  333,  332,  330,
      329,  328,  326,  324,  323,  322,  321,  320,  319,  318,
      316,  315,  313,  310,  309,  308,  307,  306,  305,  304,
      303,  301,   21,   21,   22,   22,   22,   22,   22,   22,
      300,   22,   22,   22,   22,  299,   22,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  267,  266,   22,   22,
       25,   25,  264,  263,   25,   25,   25,   25,  262,  261,

      260,   25,   25,   25,   25,   25,   25,   62,  258,   62,
       62,  257,  256,   62,   62,   62,   62,  255,  253,  252,
       62,   62,   62,   62,   62,   62,   80,   80,  251,  250,
       80,   80,   80,   80,  249,  246,  245,   80,   80,   80,
       80,   80,   80,  190,  190,  244,  243,  190,  190,  190,
      190,  242,  241,  240,  190,  190,  190,  190,  190,  190,
      192,  192,  238,  237,  192,  192,  192,  192,  236,  235,
      231,  192,  192,  192,  192,  192,  192,  233,  233,  229,
      228,  233,  233,  233,  233,  227,  226,  225,  233,  233,
      233,  233,  233,  233,  234,  234,  224,  223,  234,  234,

      234,  234,  222,  221,  220,  234,  234,  234,  234,  234,
      234,  535,  535,  535,  536,  536,  536,  537,  537,  537,
      538,  538,  538,  539,  539,  539,  540,  540,  540,  541,
      541,  541,  542,  217,  542,  548,  548,  548,  550,  550,
      550,  216,  215,  213,  211,  210,  209,  208,  207,  206,
      205,  202,  200,  199,  198,  197,  196,  195,  194,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  179,  178,
      177,  176,  175,  174,  173,  172,  170,  169,  168,  166,
      165,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  148,  142,  128,  117,  116,  114,

      112,  109,  108,  107,  106,  105,  104,  102,  101,  100,
       99,   98,   97,   96,   95,   94,   93,   91,   90,   83,
       82,   79,   75,   67,   66,   55,   51,   49,   48,   45,
       43,   41,   31,   29,   27,   24,   23,   20,   19,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534,  534,  534,  534,  534,
      534,  534,  534,  534,  534,  534
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cftoken.l"
/*	$KAME: cftoken.l,v 1.35 2005/01/12 06:06:11 suz Exp $	*/
#define YY_NO_INPUT 1
#line 6 "cftoken.l"
/*
 * Copyright (C) 2002 WIDE Project.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the project nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
#include <sys/types.h>
#include <sys/param.h>
#include <sys/socket.h>
#include <sys/queue.h>
#include <sys/time.h>

#include <netinet/in.h>

#include <errno.h>
#include <syslog.h>
#include <string.h>
#ifdef HAVE_STDARG_H
#include <stdarg.h>
#else
#include <varargs.h>
#endif

#include "dhcp6.h"
#include "config.h"
#include "common.h"
#include "y.tab.h"

#define YY_NO_UNPUT 1

extern char *configfilename;
extern int lineno;

char *configfilename;
int lineno = 1;


/* Recursion limit for includes */
#define MAX_INCLUDE_DEPTH 10

static struct include_stack {
	char *path;
	YY_BUFFER_STATE state;
	int lineno;
} incstack[MAX_INCLUDE_DEPTH];
static int incstackp = 0;


static int yy_first_time = 1;
static int yyerrorcount = 0;

#ifndef NOCONFIG_DEBUG
#ifndef YYDEBUG
#define YYDEBUG 1
#endif
static int cfdebug = 1;
#else
static int cfdebug = 0;
#endif

extern int yyparse(void);
extern int cf_post_config(void);

static void cfdebug_print(const char *, const char *, int);
void yyerror(const char *, ...);
void yywarn(char *, ...);
int cfswitch_buffer(char *);

#define DP(str) if (cfdebug) cfdebug_print(str, yytext, yyleng)
#define DECHO if (cfdebug) cfdebug_print(NULL, yytext, yyleng);
#define DNOECHO if (cfdebug) cfdebug_print(NULL, "****", yyleng);
/* abbreviations */
/* XXX */











/* XXX */

#line 948 "lex.yy.c"

#define INITIAL 0
#define S_CNF 1
#define S_IFACE 2
#define S_PREF 3
#define S_HOST 4
#define S_DUID 5
#define S_IA 6
#define S_AUTH 7
#define S_KEY 8
#define S_SECRET 9
#define S_ADDRPOOL 10
#define S_INCL 11
#define S_RAW 12

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    static void yyunput (int c,char *buf_ptr  );
#endif
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
#line 138 "cftoken.l"


	if (yy_first_time) {
		BEGIN S_CNF;
		yy_first_time = 0;
	}

	/* interface configuration */
#line 1153 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 535 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 840 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 146 "cftoken.l"
{ DECHO; BEGIN S_IFACE; return (INTERFACE); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 147 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (IFNAME);
}
	YY_BREAK
/* host configuration */
case 3:
YY_RULE_SETUP
#line 155 "cftoken.l"
{ DECHO; BEGIN S_HOST; return (HOST); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 156 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (HOSTNAME);
}
	YY_BREAK
/* address pool configuration */
case 5:
YY_RULE_SETUP
#line 164 "cftoken.l"
{ DECHO; BEGIN S_ADDRPOOL; return (ADDRPOOL); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 166 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (POOLNAME);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 173 "cftoken.l"
{ DECHO; BEGIN S_DUID; return (DUID); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 174 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (DUID_ID);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 181 "cftoken.l"
{ DECHO; return (ADDRESS); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 183 "cftoken.l"
{ DECHO; return (PREFIX); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 185 "cftoken.l"
{ DECHO; return (PREFERENCE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 187 "cftoken.l"
{ DECHO; return (SCRIPT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 189 "cftoken.l"
{ DECHO; return (DELAYEDKEY); }
	YY_BREAK
/* request */
case 14:
YY_RULE_SETUP
#line 192 "cftoken.l"
{ DECHO; return (REQUEST); }
	YY_BREAK
/* send */
case 15:
YY_RULE_SETUP
#line 195 "cftoken.l"
{ DECHO; return (SEND); }
	YY_BREAK
/* range */
case 16:
YY_RULE_SETUP
#line 198 "cftoken.l"
{ DECHO; return (RANGE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 199 "cftoken.l"
{ DECHO; return (TO); }
	YY_BREAK
/* address-pool */
case 18:
YY_RULE_SETUP
#line 202 "cftoken.l"
{ DECHO; return (ADDRESS_POOL); }
	YY_BREAK
/* DHCP options */
case 19:
YY_RULE_SETUP
#line 205 "cftoken.l"
{ DECHO; return (OPTION); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 207 "cftoken.l"
{ DECHO; return (RAPID_COMMIT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 208 "cftoken.l"
{ DECHO; return (IA_PD); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 209 "cftoken.l"
{ DECHO; return (IA_NA); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 210 "cftoken.l"
{ DECHO; return (DNS_SERVERS); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 211 "cftoken.l"
{ DECHO; return (DNS_NAME); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 212 "cftoken.l"
{ DECHO; return (SIP_SERVERS); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 213 "cftoken.l"
{ DECHO; return (SIP_NAME); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 214 "cftoken.l"
{ DECHO; return (NTP_SERVERS); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 215 "cftoken.l"
{ DECHO; return (NIS_SERVERS); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 216 "cftoken.l"
{ DECHO; return (NIS_NAME); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 217 "cftoken.l"
{ DECHO; return (NISP_SERVERS); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 218 "cftoken.l"
{ DECHO; return (NISP_NAME); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 219 "cftoken.l"
{ DECHO; return (BCMCS_SERVERS); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 220 "cftoken.l"
{ DECHO; return (BCMCS_NAME); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 221 "cftoken.l"
{ DECHO; return (REFRESHTIME); }
	YY_BREAK
/* XXX */
case 35:
YY_RULE_SETUP
#line 223 "cftoken.l"
{ DECHO; BEGIN S_RAW; return (RAW); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 224 "cftoken.l"
{ DECHO; yylval.str = strdup(yytext); return(NUMBER); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 225 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (STRING);
}
	YY_BREAK
/* provided for a backward compatibility to WIDE-DHCPv6 before Oct 1 2006 */
case 38:
YY_RULE_SETUP
#line 233 "cftoken.l"
{ DECHO; return (NIS_NAME); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 234 "cftoken.l"
{ DECHO; return (NISP_NAME); }
	YY_BREAK
/* generic options */
case 40:
YY_RULE_SETUP
#line 237 "cftoken.l"
{ DECHO; return (INFO_ONLY); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 239 "cftoken.l"
{ DECHO; return (ALLOW); }
	YY_BREAK
/* identity association */
case 42:
YY_RULE_SETUP
#line 242 "cftoken.l"
{ DECHO; BEGIN S_IA; return(ID_ASSOC); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 243 "cftoken.l"
{ DECHO; return(IA_PD); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 244 "cftoken.l"
{ DECHO; return(IA_NA); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 245 "cftoken.l"
{ DECHO; yylval.str = strdup(yytext); return(IAID); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 246 "cftoken.l"
{ DP("begin of closure"); BEGIN S_CNF; return (BCL); }
	YY_BREAK
/*
	 * interface parameters for delegated prefix configuration.
	 * when lex reads an interface name, the state will be back to
	 * S_CNF.
	 */
case 47:
YY_RULE_SETUP
#line 253 "cftoken.l"
{ DECHO; BEGIN S_IFACE; return (PREFIX_INTERFACE); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 254 "cftoken.l"
{ DECHO; return (SLA_ID); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 255 "cftoken.l"
{ DECHO; return (SLA_LEN); }
	YY_BREAK
/* duration */
case 50:
YY_RULE_SETUP
#line 258 "cftoken.l"
{ DECHO; return (INFINITY); }
	YY_BREAK
/* authentication option */
case 51:
YY_RULE_SETUP
#line 261 "cftoken.l"
{ DECHO; BEGIN S_AUTH; return (AUTHENTICATION); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 262 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (AUTHNAME);
}
	YY_BREAK
/* authentication parameters */
case 53:
YY_RULE_SETUP
#line 270 "cftoken.l"
{ DECHO; return (PROTOCOL); };
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 271 "cftoken.l"
{ DECHO; return (ALGORITHM); };
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 272 "cftoken.l"
{ DECHO; return (RDM); };
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 273 "cftoken.l"
{ DECHO; return (KEY); };
	YY_BREAK
/* authentication protocols */
case 57:
YY_RULE_SETUP
#line 276 "cftoken.l"
{ DECHO; return (DELAYED); };
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 277 "cftoken.l"
{ DECHO; return (RECONFIG); };
	YY_BREAK
/* authentication algorithms */
case 59:
YY_RULE_SETUP
#line 280 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 281 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 282 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 283 "cftoken.l"
{ DECHO; return (HMACMD5); };
	YY_BREAK
/* authentication RDM */
case 63:
YY_RULE_SETUP
#line 286 "cftoken.l"
{ DECHO; return (MONOCOUNTER); };
	YY_BREAK
/* secret keys */
case 64:
YY_RULE_SETUP
#line 289 "cftoken.l"
{ DECHO; BEGIN S_KEY; return (KEYINFO); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 290 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (KEYNAME);
}
	YY_BREAK
/* key parameters */
case 66:
YY_RULE_SETUP
#line 298 "cftoken.l"
{ DECHO; return (REALM); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 299 "cftoken.l"
{ DECHO; return (KEYID); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 300 "cftoken.l"
{ DECHO; BEGIN S_SECRET; return (SECRET); }
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 301 "cftoken.l"
{
	DNOECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (QSTRING);
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 307 "cftoken.l"
{ DECHO; return (EXPIRE); }
	YY_BREAK
/* include */
case 71:
YY_RULE_SETUP
#line 310 "cftoken.l"
{ DECHO; BEGIN S_INCL; return (INCLUDE); }
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 311 "cftoken.l"
{
	DECHO;
	yylval.str = strdup(yytext);
	BEGIN S_CNF;
	return (QSTRING);
}
	YY_BREAK
/* quoted string */
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 319 "cftoken.l"
{
		DECHO;
		yylval.str = strdup(yytext);
		return (QSTRING);
	}
	YY_BREAK
/* misc */
case 74:
YY_RULE_SETUP
#line 326 "cftoken.l"
{ ; }
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 327 "cftoken.l"
{ lineno++; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 328 "cftoken.l"
{ DP("comment"); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 329 "cftoken.l"
{
	DECHO;
	yylval.num = strtoll(yytext, NULL, 10);
	return (NUMBER);
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 334 "cftoken.l"
{ DECHO; return (SLASH); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 335 "cftoken.l"
{ DECHO; return (COMMA); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 336 "cftoken.l"
{ DP("end of sentence"); return (EOS); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 337 "cftoken.l"
{ DP("begin of closure"); return (BCL); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 338 "cftoken.l"
{ DP("end of closure"); return (ECL); }
	YY_BREAK
/* generic string */
case 83:
YY_RULE_SETUP
#line 341 "cftoken.l"
{
		DECHO;
		yylval.str = strdup(yytext);
		return (STRING);
	}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(S_CNF):
case YY_STATE_EOF(S_IFACE):
case YY_STATE_EOF(S_PREF):
case YY_STATE_EOF(S_HOST):
case YY_STATE_EOF(S_DUID):
case YY_STATE_EOF(S_IA):
case YY_STATE_EOF(S_AUTH):
case YY_STATE_EOF(S_KEY):
case YY_STATE_EOF(S_SECRET):
case YY_STATE_EOF(S_ADDRPOOL):
case YY_STATE_EOF(S_INCL):
case YY_STATE_EOF(S_RAW):
#line 347 "cftoken.l"
{
		if (--incstackp < 0)
			yyterminate();
		else {
			yy_delete_buffer(YY_CURRENT_BUFFER);
			free(incstack[incstackp + 1].path);
			configfilename = incstack[incstackp].path;
			lineno = incstack[incstackp].lineno;
			yy_switch_to_buffer(incstack[incstackp].state);
		}
	}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 359 "cftoken.l"
ECHO;
	YY_BREAK
#line 1771 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 535 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 535 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 534);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif	/* ifndef YY_NO_UNPUT */

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 359 "cftoken.l"


static void
cfdebug_print(const char *w, const char *t, int l)
{
	if (w) {
		d_printf(LOG_DEBUG, FNAME,
		    "<%d>%s [%s] (%d)", yy_start, w, t, l);
	} else {
		d_printf(LOG_DEBUG, FNAME,
		    "<%d>[%s] (%d)", yy_start, t, l);
	}
}

static void
yyerror0(int level, const char *s, va_list ap)
{
	char ebuf[BUFSIZ], *bp, *ep;

	bp = ebuf;
	ep = ebuf + sizeof(ebuf);
	bp += snprintf(bp, ep - bp, "%s %d: ", configfilename, lineno);
	if (bp < ep)
		bp += vsnprintf(bp, ep - bp, s, ap);

	d_printf(level, FNAME, ebuf);
}

void
yyerror(const char *s, ...)
{
	va_list ap;
#ifdef HAVE_STDARG_H
	va_start(ap, s);
#else
	va_start(ap);
#endif
	yyerror0(LOG_ERR, s, ap);
	va_end(ap);
	yyerrorcount++;
}

void
yywarn(char *s, ...)
{
	va_list ap;
#ifdef HAVE_STDARG_H
	va_start(ap, s);
#else
	va_start(ap);
#endif
	yyerror0(LOG_WARNING, s, ap);
	va_end(ap);
}

int
cfswitch_buffer(char *incl)
{
	char *path = qstrdup(incl);
	FILE *fp;

	if (incstackp >= MAX_INCLUDE_DEPTH) {
		d_printf(LOG_ERR, FNAME, "cfparse: includes nested too deeply");
		return (-1);
	}
	incstack[incstackp].path = configfilename;
	incstack[incstackp].state = YY_CURRENT_BUFFER;
	incstack[incstackp].lineno = lineno;

	fp = fopen(path, "r");
	if (fp == NULL) {
		d_printf(LOG_ERR, FNAME, "cfparse: fopen(%s): %s",
			path, strerror(errno));
		if (errno == ENOENT)
			return (0);
		return (-1);
	}
	incstackp++;
	configfilename = path;
	lineno = 1;
	yy_switch_to_buffer(yy_create_buffer(fp,YY_BUF_SIZE));

	BEGIN(S_CNF);

	return (0);
}

int
cfparse(const char *conf)
{

	free(configfilename);
	configfilename = strdup(conf);

	if ((yyin = fopen(configfilename, "r")) == NULL) {
		d_printf(LOG_ERR, FNAME, "cfparse: fopen(%s): %s",
			configfilename, strerror(errno));
		if (errno == ENOENT)
			return (0);
		return (-1);
	}

	if (yyparse() || yyerrorcount) {
		if (yyerrorcount) {
			yyerror("fatal parse failure: exiting (%d errors)",
				yyerrorcount);
		} else
			yyerror("fatal parse failure: exiting");
		return (-1);
	}

	return (cf_post_config());
}

